pipeline {

    agent any

    options {
        skipDefaultCheckout(true)
    }

    parameters {

        string(
            name: 'BRANCH_NAME',
            defaultValue: 'main',
            description: 'Branche à construire'
        )

        choice(
            name: 'ENV',
            choices: ['dev', 'staging', 'prod'],
            description: 'Environnement cible'
        )
    }

    stages {

        stage('Checkout') {

            steps {

                echo "📥 Checkout de la branche ${params.BRANCH_NAME}"

                git(
                    branch: params.BRANCH_NAME,
                    url: 'https://github.com/bettaiebmedali/jenkins-pipeline.git'
                )
            }
        }

        stage('Build') {

            steps {

                dir('jenkins-param-lab') {

                    echo "🛠️ Build de la branche ${params.BRANCH_NAME} pour ${params.ENV}"

                    sh "mvn clean compile -P${params.ENV}"
                }
            }
        }

        stage('Test') {

            steps {

                dir('jenkins-param-lab') {

                    echo '✅ Exécution des tests unitaires...'

                    sh 'mvn test'
                }
            }
        }
    }
}