pipeline {

    agent {
        docker {
            image 'maven:3.9.9-eclipse-temurin-21'
            reuseNode true
        }
    }

    options {
        skipDefaultCheckout(true)
    }

    parameters {

        string(
            name: 'BRANCH_NAME',
            defaultValue: 'feature-test',
            description: 'Branche à construire'
        )

        choice(
            name: 'ENV',
            choices: ['dev', 'staging', 'prod'],
            description: 'Environnement cible'
        )
    }

    stages {

        stage('Checkout') {
            steps {
                echo "📥 Checkout de la branche ${params.BRANCH_NAME}"

                git(
                    branch: params.BRANCH_NAME,
                    url: 'https://github.com/bettaiebmedali/jenkins-pipeline.git'
                )
            }
        }

        stage('Build') {
            steps {
                dir('jenkins-param-lab') {

                    echo "🛠️ Build de ${params.BRANCH_NAME} pour ${params.ENV}"

                    sh 'java -version'
                    sh 'mvn -version'

                    sh "mvn clean compile -P${params.ENV}"
                }
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-param-lab') {

                    echo '✅ Exécution des tests...'

                    sh 'mvn test'
                }
            }
        }
    }
}